src/tlshd/config.c, src/tlshd/keyring.c, src/tlshd/tlshd.h
Use the library function 'find_key_by_type_and_desc()' and drop our hand-crafted lookup for keyrings.
Signed-off-by: Hannes Reinecke <hare@suse.de>
=> keyring: use 'find_key_by_type_and_desc()'

src/tlshd/keyring.c
Logging functions reference a variable 'buf' which is never set.
Signed-off-by: Hannes Reinecke <hare@suse.de>
=> keyring: fixup logging display

configure.ac, src/tlshd/client.c, src/tlshd/netlink.c, src/tlshd/server.c
Hi all,
here are two patches which are required to have ktls-utils compile with older libraries.
Signed-off-by: Hannes Reinecke <hare@suse.de>
=> Compability patches

src/tlshd/client.c, src/tlshd/keyring.c, src/tlshd/server.c, src/tlshd/tlshd.h
When loading the private key with material from a keyring, tlshd did not initialize the static tlshd_privkey. Instead, it accidentally filled in a local copy. This lead to a failure when performing the handshake, with a general error message of:
>  tlshd[7823]: gnutls: No supported cipher suites have been found. (-87)
To fix this issue, simply supply the pointer to tlshd_privkey, like already done when loading the certificate from the config file.
=> tlshd: fix init of privkey from keyring

configure.ac, src/tlshd/config.c
WanzenBug says:
> A lot of times certificates and keys are set up in a way they can
> be rotated by changing symlinks. For example, this is common when
> using Let's Encrypt with certbot, where the canonical location for
> key material is /etc/letsencrypt/live/<host>/privkey.pem, which
> are symlinks to
> /etc/letsencrypt/archive/<host>/privkey$GENERATION.pem. Every time
> the certificate gets renewed, the symlinks are updated.
Our security reviewers agree that there is no need for the extra restriction, as most modern Linux distributions have fs.protected_symlinks to prevent TOCTOU symlink vulnerabilities.
Addresses Issue #37.
=> tlshd: Remove tlshd_file_open()

src/tlshd/main.c
- help doesn't require argument
- exit after usage is printed
=> fix handling of command like options

src/tlshd/client.c, src/tlshd/config.c, src/tlshd/keyring.c, src/tlshd/server.c, src/tlshd/tlshd.h
This patch adds support for chained certs (e.g. client/server .pem file which includes an intermediate CA cert as well as the actual client/server cert).
Tested with a client/server NFS setup (using xprtsec=mtls) where only the root CA is in the system trust store and both the client and server use chained certificates with an intermediate CA as part of the cert.
Fixes: #44
=> tlshd: Add support for chained certs

src/tlshd/client.c, src/tlshd/handshake.c, src/tlshd/ktls.c, src/tlshd/tlshd.h
PSK ClientHello only sends a single PSK value, which matches only to one hash algorithm. So we should restrict the announced hash values to only the correct one.
=> Restrict announced hash value for PSK

src/tlshd/client.c, src/tlshd/config.c, src/tlshd/ktls.c, src/tlshd/server.c, src/tlshd/tlshd.conf.man, src/tlshd/tlshd.h
PSK mode has its own rules which cipher suites should be selected; as we're only ever sending a single PSK for each ClientHello we really should only include matching cipher suites to avoid the server selecting a mismatching cipher suite.
=> Fixup priority setting

README, README.md
It was noted in Issue #52 that the README needs to mention the minimum kernel support required for ktls-utils to work.
It turns out not to be a straightforward thing to add. Support for in-kernel TLS handshakes were added to the SunRPC server in v6.5; to the SunRPC client in v6.6; and for NVMe in later releases. Moreover, some of this has been backported into older distribution kernels. Keeping track of distribution kernels is not possible here.
=> README: Indicate additional kernel dependency for ktls-utils

src/tlshd/ktls.c, src/tlshd/tlshd.h
One memory leak in an error flow and one implicit signedness change.
=> Address two issues found in a recent Parfait run

ChangeLog, NEWS, README, README.md, configure.ac
ktls-utils 0.11 - 2024-06-05
* Add support for chained certs
* Move to-do items to the GitHub issue tracker
* Fix minor bugs
=> Release ktls-utils 0.11

configure.ac, src/tlshd/Makefile.am, src/tlshd/client.c, src/tlshd/handshake.c, src/tlshd/netlink.c, src/tlshd/quic.c, src/tlshd/server.c, src/tlshd/tlshd.h
This patch adds QUIC handshake support to tlshd, utilizing GnuTLS for TLS message handling and integrating with existing code for PSK and certificate verification. The feature is conditionally compiled based on kernel and GnuTLS capabilities. See each commit for more details.
With the feedback from Chuck Lever, v1->v2:
- Delete the basic test description from the cover letter.
- Refactor tlshd_service_socket() by Chuck in patch 1/3.
- Include socket ip_proto in tlshd_handshake_parms in patch 2/3.
- Replace HAVE_QUIC with HAVE_GNUTLS_QUIC and move the check for QUIC handshakes into the switch statement in tlshd_service_socket() in patch 3/3.
With more feedback from Chuck, v2->v3:
- use switch statement for different ip_proto and set parms.session_status to EOPNOTSUPP in …
=> tlshd: add support for quic handshake

src/tlshd/server.c, src/tlshd/tlshd.h
Improve the logging message when looking up the psk to include the TLS identity for better debugging.
=> tlshd: improve error logging for tlshd_server_psk_cb()

.github/workflows/makefile.yml, README, README.md, src/tlshd/tlshd.conf.man, src/tlshd/tlshd.man
Indicate that ktls-utils is no longer an experimental protocol, but may be used on production systems as part of an enterprise Linux distribution.
Addresses issue #69
=> Remove package "experimental" status

README, README.md, configure.ac
Since "experimental" and "prototype" has been removed, make the next full release of ktls-utils be the one-dot-zero release.
=> Prepare next ktls-utils release to be 1.0.0 (no release date planned yet)

configure.ac, src/tlshd/Makefile.am
tlshd depends on libnl-genl3, thus add a explicit check if the library is available.
Fixes: #77
=> tlshd: Ensure libnl-genl3 is available

src/tlshd/config.c
A common use case for tlshd is to authenticate TLS sessions for the nvme subsystem. Currently, the user has to explicitly list a keyring (even the defautl one) in the configuration file so that tlshd running as daemon (started via systemd) to find any key.
Thus always link the default .nvme keyring into the current session, which makes the daemon work out of the box for default configurations.
@hreinecke
=> tlshd: always link .nvme default keyring into the session

.github/workflows/makefile.yml, ChangeLog, NEWS, README, README.md, configure.ac
Prepare for ktls-utils 1.0 by creating a first release candidate.
=> Release ktls-utils 1.0-rc1

src/tlshd/handshake.c
We've had some QE work that's created a condition (some types of connection instability) where the handshake attempt has timed out.  When this happens, tlshd sends EACESS back to the kernel.  However, the kernel may not be expecting this error in the context of some NFS operations, for example: writeback.  It can handle ETIMEDOUT, and we would like the kernel to perform its normal hard/soft retry routines for this case to re-connect to the server.
Add an error switch that clearly denotes the error paths we'd like to send back to the kernel.  For SUNRPC, there are other insteresting errors that might be included (see call_conenct_status() in net/sunrpc/clnt.c), but are ommitted here because we don't have evidence of them in the wild
=> tlshd: Pass ETIMEDOUT from gnutls to kernel

src/tlshd/quic.c
SOL_QUIC should be used for the cmsg_level in send/recvmsg(). Although in many transport protocols IPPROTO_XXX == SOL_XXX, IPPROTO_QUIC != SOL_QUIC in linux quic.
Fixes: 43a15fed2f33 ("tlshd: add support for quic handshake")
=> tlshd: replace IPPROTO_QUIC with SOL_QUIC for cmsg_level in quic

README, README.md, configure.ac, src/tlshd/config.c, src/tlshd/main.c
A handful of bug fixes since -rc1.
=> ktls-utils 1.0, 2nd release candidate

src/tlshd/config.c
ALLPERMS exists in glibc, but not on musl, so we manually define TLSHD_ACCESSPERMS and use that instaed. This fixes building on musl systems.
=> tlshd: Define TLSHD_ACCESSPERMS instead of using ALLPERMS to fix musl build

configure.ac
AC_CHECK_FILE doesn't work when cross-compiling [1], which breaks a lot of use cases (like OpenEmbedded for one). Autoconf supports AC_CHECK_HEADER which can be used instead and is more robust [2] so let's use that instead.
1: https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Files.html
2: https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Generic-Headers.html
=> tlshd: configure.ac: Use AC_CHECK_HEADER instead of AC_CHECK_FILE

src/tlshd/client.c, src/tlshd/server.c
The call to gnutls_global_deinit() in tlshd_quic_clienthello_handshake() and tlshd_quic_serverhello_handshake() is redundant, as it is already invoked by their common caller tlshd_service_socket(). Remove these unbalanced deinitialization calls to avoid potential misuse or double deinitialization.
Additionally, fix the error handling to assign -ret to session_status instead of ret for consistency with other error paths.
=> tlshd: remove redundant gnutls_global_deinit()

.github/workflows/makefile.yml, ChangeLog, NEWS, README, README.md, configure.ac, src/tlshd/client.c, src/tlshd/config.c, src/tlshd/handshake.c, src/tlshd/keyring.c, src/tlshd/ktls.c, src/tlshd/log.c, src/tlshd/main.c, src/tlshd/netlink.c, src/tlshd/server.c, src/tlshd/tlshd.conf, src/tlshd/tlshd.conf.man, src/tlshd/tlshd.h
Finalize the set of commits to appear in ktls-utils release 1.2.
=> ktls-utils 1.2 release

src/tlshd/client.c, src/tlshd/server.c
This reverts commit d507771d618bbb2d264af20d2305803ea9bf368e, which seems to break mTLS.  The symptoms for NFS are that a mount seems to succeed but then all operations on the client return `EPERM`.
Use `g_array_append_val()` to store the peer IDs, as is done in in the PSK callback functions.
=> Revert "tlshd: Do not return remote peer IDs for x.509 handshakes"

src/tlshd/client.c, src/tlshd/server.c
This patch fixes these compiling errors with QUIC enabled:
client.c: In function ‘tlshd_quic_client_set_x509_session’: client.c:489:43: error: ‘xcred’ undeclared (first use in this function);
did you mean ‘cred’?
489 |         ret = tlshd_client_get_truststore(xcred);
|                                           ^~~~~
|                                           cred
client.c:489:43: note: each undeclared identifier is reported only once
for each function it appears in
client.c: In function ‘tlshd_quic_client_set_psk_session’: client.c:544:31: error: incompatible types when initializing type
‘key_serial_t’ {aka ‘int’} using type ‘GArray’ {aka ‘struct _GArray’}
544 |         key_serial_t peerid = conn->parms->peerids[0];
|                               ^~~~
server.c: In function …
=> tlshd: fix a couple of compiling errors with QUIC enabled

src/tlshd/server.c
NFSD depends on seeing a non-zero remote peerid to know when the new session has been authenticated via mTLS. NFSD does not parse the incoming certificate, but tlshd tries to make it available to the kernel and kernel consumers by adding it to the SPEC keyring.
However, add_key(2) /does/ parse the incoming certificate, and any parsing failure results in failure to add the certificate to the keyring. A parsing failure might be the result of an unrecognized (but nonetheless valid) signature encryption algorithm. This will become even more of a hazard as support for PQ signing algorithms is introduced.
Key insertion failure causes tlshd to use TLS_NO_PEERID as the remote peer ID. When this happens, a session which is successfully authenticated by GnuTLS looks unauthenticated to NFSD, …
=> tlshd: Kernel should not parse incoming client certificates

configure.ac, man/Makefile.am, man/man5/Makefile.am, man/man5/tlshd.conf.5, man/man8/Makefile.am, man/man8/tlshd.8, src/tlshd/Makefile.am
Initially I copied the nfs-utils style of situating man pages in the src/ tree along side the tools they document.
However, build systems, package integrators, and development tools appear to expect man pages to reside under:
${topdir}/man/man?
And I'm beginning to encounter some naming conflicts under src/tlshd/.
Relocate the man pages from src/ and construct a proper section- based man folder hierarchy.
=> Relocate man pages

src/tlshd/ktls.c
Commit 9253f9d added the use of the @SYSTEM keyword as the initial keyword in the priority string used by tlshd.  Unfortunately @SYSTEM doesn't appear to work on systems that do not have a system-wide library configuration set up.
Instead of trying to pick an initial keyword that will work on all systems, let's instead use gnutls_priority_init2() with the GNUTLS_PRIORITY_INIT_DEF_APPEND flag instead.  That will *append* our priority string to the default options.
Fixes: 9253f9d ("tlshd: Fix priority string to allow PQC")
Tested-by: Alistair Francis <alistair.francis@wdc.com>
Reviewed-by: Alistair Francis <alistair.francis@wdc.com>
Reviewed-by: Hannes Reinecke <hare@suse.de>
=> tlshd: fix priority cache initialization
